name: Continous Integration

on:
 push:
  branches: 
    - main
jobs:
  continous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout to branch'
        uses: actions/checkout@v3
      
      - name: Setup Node.js env
        uses: actions/setup-node@v2
        with: 
          node-version: 18

      - name: npm install, build and test
        run: | 
          cd javascript/
          npm install
          echo "Building something..."
          npm run test